#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

if [ ! -d $OPENSHIFT_DATA_DIR/bin ]; then

    cd $OPENSHIFT_TMP_DIR
    wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-2.6.3.tgz
    tar -xzf mongodb-linux-x86_64-2.6.3.tgz 
    mv mongodb-linux-x86_64-2.6.3/bin/mongod  mongodb-linux-x86_64-2.6.3/bin/mongo $OPENSHIFT_MONGOX_DIR/mongo/bin

fi

